apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: myapp
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "" # Leave empty if using system-assigned identity
    keyvaultName: "olhabuchynskavault" # Replace with your Key Vault name
    cloudName: "AzurePublicCloud"
    objects: |
      array:
        - objectName: "argo-admin-pass"
          objectType: "secret"
    tenantId: "8d1157bb-1f96-415f-824b-ab0a29485d7d"
